#include        "../types.h"
#include        "../x6502.h"
#include        "../fceu.h"
#include	"../ppu.h"
#include        "../cart.h"
#include        "../memory.h"
#include	"../sound.h"
#include	"../state.h"
#include	"../cheat.h"
#include	<string.h>
#include <malloc.h>
