name: FCE Ultra GX Build

on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.image }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii", "GameCube", "WiiU"]
    container: ghcr.io/extremscorner/libogc2:latest

    steps:
    - name: Checkout fceugx repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build and install libmocha
      if: ${{ matrix.image == 'WiiU' }}
      run: |
        git clone --depth 1 https://github.com/dborth/libmocha.git /tmp/libmocha
        cd /tmp/libmocha && make install

    - name: Build and install libdvm
      if: ${{ matrix.image == 'WiiU' }}
      run: |
        git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/dborth/libdvm.git /tmp/libdvm
        cd /tmp/libdvm && make install

    - name: Build and install libsmb2
      run: |
        git clone --depth 1 https://github.com/dborth/libsmb2.git /tmp/libsmb2
        cd /tmp/libsmb2
        if [ "${{ matrix.image }}" = "Wii" ]; then
          make -f Makefile.platform wii_install
        elif [ "${{ matrix.image }}" = "GameCube" ]; then
          make -f Makefile.platform gc_install
        elif [ "${{ matrix.image }}" = "WiiU" ]; then
          make -f Makefile.platform wiiu_install
        fi

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j3

    - name: Copy Wii artifacts
      if: ${{ matrix.image == 'Wii' }}
      run: |
        mkdir -p dist/FCEUltraGX-Wii/apps/fceugx
        mkdir -p dist/FCEUltraGX-Wii/fceugx/roms
        mkdir dist/FCEUltraGX-Wii/fceugx/cheats
        mkdir dist/FCEUltraGX-Wii/fceugx/saves
        touch dist/FCEUltraGX-Wii/fceugx/roms/romsdir
        touch dist/FCEUltraGX-Wii/fceugx/cheats/cheatsdir
        touch dist/FCEUltraGX-Wii/fceugx/saves/savesdir
        cp hbc/* dist/FCEUltraGX-Wii/apps/fceugx/
        cp executables/fceugx-wii.dol dist/FCEUltraGX-Wii/apps/fceugx/boot.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'Wii' }}
      with:
        name: FCEUltraGX-Wii
        path: |
          dist/FCEUltraGX-Wii/

    - name: Build GameCube
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        make -f Makefile.gc -j3

    - name: Copy GameCube artifact
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        mkdir -p dist/FCEUltraGX-GameCube
        cp executables/fceugx-gc.dol dist/FCEUltraGX-GameCube/

    - name: Upload GameCube artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'GameCube' }}
      with:
        name: FCEUltraGX-GameCube
        path: |
          dist/FCEUltraGX-GameCube/

    - name: Build Wii U
      if: ${{ matrix.image == 'WiiU' }}
      run: |
        make -f Makefile.wiiu -j3

    - name: Copy Wii U artifact
      if: ${{ matrix.image == 'WiiU' }}
      run: |
        mkdir -p dist/FCEUltraGX-WiiU
        cp executables/fceugx-wiiu.wuhb dist/FCEUltraGX-WiiU/

    - name: Upload Wii U artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'WiiU' }}
      with:
        name: FCEUltraGX-WiiU
        path: |
          dist/FCEUltraGX-WiiU/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout fceugx repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Re-zip artifacts
      run: |
        cd dist/FCEUltraGX-Wii
        rm -r fceugx/cheats/*
        rm -r fceugx/roms/*
        rm -r fceugx/saves/*
        zip -r ../FCEUltraGX-Wii.zip *
        cd ../FCEUltraGX-GameCube
        zip -r ../FCEUltraGX-GameCube.zip *

    - name: Update Git Tag
      run: |
        git tag -f Pre-release
        git push -f origin Pre-release

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: false
        tag: Pre-release
        artifacts: "dist/*.zip"
