name: FCE Ultra GX Build

on: [push, pull_request]

jobs:
  build:
    name: Build FCE Ultra GX
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii", "GameCube"]
    container: devkitpro/devkitppc:latest
 
    steps:
    - name: Checkout fceugx repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j2     
    
    - name: Copy Wii artifacts
      if: ${{ matrix.image == 'Wii' }}
      run: | 
        mkdir -p dist/FCEUltraGX/apps/fceugx
        mkdir -p dist/FCEUltraGX/fceugx/roms
        mkdir dist/FCEUltraGX/fceugx/cheats
        mkdir dist/FCEUltraGX/fceugx/saves       
        touch dist/FCEUltraGX/fceugx/roms/romsdir
        touch dist/FCEUltraGX/fceugx/cheats/cheatsdir
        touch dist/FCEUltraGX/fceugx/saves/savesdir
        cp hbc/* dist/FCEUltraGX/apps/fceugx/
        cp executables/fceugx-wii.dol dist/FCEUltraGX/apps/fceugx/boot.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v2
      if: ${{ matrix.image == 'Wii' }}
      with: 
        name: FCEUltraGX
        path: |
         dist/FCEUltraGX/
     
    - name: Build GameCube
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        make -f Makefile.gc -j2
        
    - name: Copy GameCube artifact
      if: ${{ matrix.image == 'GameCube' }}
      run: | 
        mkdir -p dist/FCEUltraGX-GameCube
        cp executables/fceugx-gc.dol dist/FCEUltraGX-GameCube/
        
    - name: Upload GameCube artifact
      uses: actions/upload-artifact@v2
      if: ${{ matrix.image == 'GameCube' }}
      with: 
        name: FCEUltraGX-GameCube
        path: |
         dist/FCEUltraGX-GameCube/
