name: FCE Ultra GX Build

on: [push, pull_request]

jobs:
  build:
    name: Build FCE Ultra GX
    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: |
        make -j2
    
    - name: Copy files
      run: | 
        mkdir -p dist/FCEUltraGX/apps/fceugx
        mkdir -p dist/FCEUltraGX/fceugx/roms
        mkdir dist/FCEUltraGX/fceugx/cheats
        mkdir dist/FCEUltraGX/fceugx/saves
        mkdir dist/FCEUltraGX-GameCube/
        touch dist/FCEUltraGX/fceugx/roms/romsdir
        touch dist/FCEUltraGX/fceugx/cheats/cheatsdir
        touch dist/FCEUltraGX/fceugx/saves/savesdir
        cp hbc/* dist/FCEUltraGX/apps/fceugx/
        cp executables/fceugx-wii.dol dist/FCEUltraGX/apps/fceugx/boot.dol
        cp executables/fceugx-gc.dol dist/FCEUltraGX-GameCube/

    - name: Upload Wii Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: FCEUltraGX
        path: |
         dist/FCEUltraGX/
    
    - name: Upload GameCube Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: FCEUltraGX-GameCube
        path: |
         dist/FCEUltraGX-GameCube/
